apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: testradix1
spec:
  environments:
    - name: prod
      build:
        from: release
    - name: qa
      build:
        from: master
  components:
    - name: app
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 8000
      public: true
      environmentConfig:
        - environment: prod
          replicas: 1
          variables:
            PYFLASK_VARIABLE_TRY: "python-flask-env-var-test"
        - environment: qa
          replicas: 2
          variables:
            PYFLASK_VARIABLE_TRY: "python-flask-env-var-test"
